### ISSUE TITLE
Controller for mouse

### ISSUE THREAD

**Issue by gerbil** [maxpoletaev/dendy#4]
Idea is to map J - to left click, K - to right click

**Comment by maxpoletaev** [comment]
Just trying to understand, why might someone need this?

**Comment by gerbil** [comment]
To play with mouse obviously.. since controller is not available

**Comment by maxpoletaev** [comment]
I never considered this project to be used seriously by anyone, since there are plenty of production-grade emulators out there with better control options (I've never seen one that allows the mapping of mouse buttons to gamepad buttons, though). This is the reason why I'm not adding remappable controls and other features that are expected in a modern emulator. I'm just doing this for fun and to learn more about emulation in general and as a reference for anyone who wants to learn about it, so there isn’t really a goal to make it usable for the general public.

I do have gamepad support in mind, as it is natively supported by raylib and easy to implement, but I'm not sure if mouse controls of this kind are worth the effort, given that the left mouse button is already reserved for Lightgun games.
